### ISSUE TITLE
support capturing 1..n fields

### ISSUE THREAD

**Issue by hokiegeek2** [neguse/fluent-plugin-extract-json#2]
@neguse first of all, really cool plugin! Combining this with [flatten-hash](https://github.com/kazegusuri/fluent-plugin-flatten-hash) almost gets where I want to go. The next step is to enable extraction of 2..n JSON element-value pairs

**Comment by neguse** [comment]
@hokiegeek2 Could you tell me concrete example what you want to do?

If you want to filter some keys of a record, you may use [record_transformer](https://docs.fluentd.org/v1.0/articles/filter_record_transformer) plugin.

# Example

This example shows how to filter some keys of a record. `k1`, `k2` and `k3` keys are kept, and other keys are filtered out.

## Config

```
  <source>
    @type http
    port 8888
    bind 0.0.0.0
    body_size_limit 32m
    keepalive_timeout 10s
  </source>
  <filter>
    @type record_transformer
    renew_record true
    keep_keys k1, k2, k3
  </filter>
  <match test>
    @type stdout
  </match>
```

## Test input

```
curl -X POST -d 'json={"k1":"v1","k2":"v2","k3":"v3","k4":"ignored"}' http://localhost:8888/test
```

## Result

```
2018-08-22 13:19:48 +0000 test: {"k1":"v1","k2":"v2","k3":"v3"}
```

**Comment by hokiegeek2** [comment]
@neguse Thanks, and it turns out, record_transformer enabled me to extract JSON elements and send them to separate output destinations.
